# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2fde4854a1ec0555af9dd60636cc1c85afb0dce789be819034f16e860e2bd84b569afc6cb3e5de722fd1def63fa8f604e55794edccd0ad030fce92068a4cd6c

test:
  secret_key_base: 69a3b9aedddee95bd0546d9d1fbe508ab88a6f7d0e29ab246cc37e867d1b0cda9b66c12649c0e85761e044e1cf9e1dda10c552c08eed8712320803fa48afa087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
